version: '3.9'

services:
  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - backend
    env_file: .env
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - frontend
      - backend
    env_file: .env
    
networks:
  frontend:
  backend: